[package]
name = "cosey"
version = "0.4.0"
authors = ["Nicolas Stalder <n@stalder.io>"]
license = "Apache-2.0 OR MIT"
description = "Data types and serde for public COSE_Keys"
categories = ["embedded", "encoding", "no-std"]
keywords = ["cose", "cbor", "rust", "no-std"]
repository = "https://github.com/ycrypto/cosey"
readme = "README.md"
edition = "2021"

[dependencies]
heapless-bytes = "0.3.0"
serde = "1.0"
serde_derive = "1.0"
serde_repr = "0.1.6"
